/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testnumerical;

import java.math.BigDecimal;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Frost
 */
public class InitialBoundsOpen extends javax.swing.JFrame {

    /**
     * Creates new form InitialUpperLower
     */
    String terms;
    String derive;
    BigDecimal[] coefficients;
    int[] degree;
    BigDecimal bounds;
 
    BigDecimal marginErrorValue;
    int modeOfIter;
    int noIter;
    BigDecimal[] deriveCoefficient;
    int[] deriveDegree;
    public InitialBoundsOpen(String terms,String derive, BigDecimal[] coefficients, int[] degree, BigDecimal[] deriveCoefficient, int[] deriveDegree) {
        
        this.terms=terms;
        this.coefficients=coefficients;
        this.degree=degree;
        this.derive=derive;
        this.deriveCoefficient=deriveCoefficient;
        this.deriveDegree=deriveDegree;
        System.out.println(terms);
        initComponents();
        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(MarginError);
        buttonGroup.add(noIteration);
        setVisible(true);
        setTitle("Numerical Methods");
        setLocationRelativeTo(null);
        pack();
        
      
     
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Bounds = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MarginError = new javax.swing.JRadioButton();
        noIteration = new javax.swing.JRadioButton();
        IterationField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INITIAL BOUNDS (Newton Rhapson)");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Boundary:");

        Bounds.setBackground(new java.awt.Color(255, 255, 255));
        Bounds.setForeground(new java.awt.Color(51, 51, 51));

        submitButton.setBackground(new java.awt.Color(0, 0, 0));
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(terms);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MODE OF ITERATION");

        MarginError.setBackground(new java.awt.Color(204, 204, 255));
        MarginError.setForeground(new java.awt.Color(0, 0, 0));
        MarginError.setText("MARGIN OF ERROR");
        MarginError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarginErrorActionPerformed(evt);
            }
        });

        noIteration.setBackground(new java.awt.Color(204, 204, 255));
        noIteration.setForeground(new java.awt.Color(0, 0, 0));
        noIteration.setText("NO. OF ITERATION");
        noIteration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noIterationActionPerformed(evt);
            }
        });

        IterationField.setBackground(new java.awt.Color(255, 255, 255));
        IterationField.setForeground(new java.awt.Color(0, 0, 0));
        IterationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IterationFieldActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(derive);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(IterationField, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(noIteration, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(MarginError))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 320, Short.MAX_VALUE)
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Bounds, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Bounds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(IterationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MarginError)
                .addGap(18, 18, 18)
                .addComponent(noIteration)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(submitButton)))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
   // Parse the upper and lower values as BigDecimal

   //  evaluateFx eval=new evaluateFx();
   // eval.ComputeFx(upper, coefficients, degree);

   String stringBounds = Bounds.getText();
   BigDecimal bounds;
   try {
       bounds = new BigDecimal(stringBounds);

       //  eval.ComputeFx(upper, coefficients, degree);
       //  eval.ComputeFx(lower,coefficients,degree);

   } catch (NumberFormatException e) {
       JOptionPane.showMessageDialog(InitialBoundsOpen.this, "Bound must be a number","Error",JOptionPane.ERROR_MESSAGE);
       return;
   }
if (bounds.compareTo(BigDecimal.ZERO) == 0) {
    JOptionPane.showMessageDialog(InitialBoundsOpen.this, "Bound must not be 0","Error",JOptionPane.ERROR_MESSAGE);
    return;
}
   
   this.bounds = bounds;

   // Parse the iteration value and mode of iteration
   String inputText = IterationField.getText();
   boolean marginErrorRadio = MarginError.isSelected();
   MarginError.setSelected(true);
   if (marginErrorRadio) {
       // Check that the margin error value is between 0 and 1 (exclusive)
       BigDecimal marginErrorValue;
       try {
           marginErrorValue = new BigDecimal(inputText);
       } catch (NumberFormatException e) {
           JOptionPane.showMessageDialog(InitialBoundsOpen.this, "Margin error must be a real number.","Error",JOptionPane.ERROR_MESSAGE);
           return;
       }
       if (marginErrorValue.compareTo(BigDecimal.ZERO) <= 0 || marginErrorValue.compareTo(BigDecimal.ONE) >= 0) {
           JOptionPane.showMessageDialog(InitialBoundsOpen.this, "Margin error must be between 0 and 1 (exclusive).","Error",JOptionPane.ERROR_MESSAGE);
           return;
       }

       // Set the mode of iteration and margin error value
       this.modeOfIter = 1;
       this.marginErrorValue = marginErrorValue;
   } else {
       // Parse the number of iterations
       int noIter;
       try {
           noIter = Integer.parseInt(inputText);
       } catch (NumberFormatException e) {
           JOptionPane.showMessageDialog(InitialBoundsOpen.this, "Number of iterations must be a positive integer.","Error",JOptionPane.ERROR_MESSAGE);
           return;
       }
       if (noIter <= 0) {
           JOptionPane.showMessageDialog(InitialBoundsOpen.this, "Number of iterations must be a positive integer.","Error",JOptionPane.ERROR_MESSAGE);
           return;
       }

       // Set the mode of iteration and number of iterations
       this.modeOfIter = 2;
       this.noIter = noIter;
   }

   // Close the dialog

   int noIter = getNoIter();
   BigDecimal marginError = getError();
   int modeIterNewton = getModeIter();

   System.out.println("bounds: " + bounds);

   System.out.println("NoIter: " + noIter);
   System.out.println("Margin of Error " + marginError);
   System.out.println("Mode of Iter:" + modeIterNewton);

   calcNewton newton = new calcNewton();
   if (modeIterNewton == 1) {
       newton.newtonMarginError(terms, derive, degree, coefficients, deriveDegree, deriveCoefficient, bounds, marginError);
   } else {
       newton.newtonNoIter(terms, derive, degree, coefficients, deriveDegree, deriveCoefficient, bounds, noIter);
   }
    
    }//GEN-LAST:event_submitButtonActionPerformed
    
    public BigDecimal getError(){
    return marginErrorValue;
    }
    
    public int getNoIter(){
    return noIter;
    }
    public int getModeIter(){
    return modeOfIter;}
    
    private void MarginErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarginErrorActionPerformed

    }//GEN-LAST:event_MarginErrorActionPerformed

    private void IterationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IterationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IterationFieldActionPerformed

    private void noIterationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noIterationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noIterationActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        homePage home=new homePage();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        PolynomialGUIOpen gui= new PolynomialGUIOpen();
    }//GEN-LAST:event_jButton1ActionPerformed

    public BigDecimal getbounds(){
    return bounds;}
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bounds;
    private javax.swing.JTextField IterationField;
    private javax.swing.JRadioButton MarginError;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton noIteration;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
